spring.application.name: learner-node
server.port: 8810
---
cluster:
  kafka:
    groupId: command-log-learner-group

spring.datasource:
  username: root
  password: root

---
learner:
  bufferSize: 32
  pollInterval: 100
  maxSnapshotCheckCircles: 50
  snapshotFragmentSize: 1000
  snapshotLifeTime: 10
