spring.application.name: follower-node-1
server.port: 8805
---

server:
  grpc:
    port: 9510

cluster:
  kafka:
    groupId: command-log-follower-group-1

spring.datasource:
  username: reader
  password: reader

---
follower:
  bufferSize: 1024
  pollInterval: 100
